# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practical_Movie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practical_Movie

  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'ObjectMapper'

end
